import { describe, expect, it } from "vitest";

import {
  buildSupportDiagnosticsPayload,
  formatSupportIssueSubmissionError,
  getSanitizedSupportPageUrl,
  recordSupportNetworkLog,
  reportSupportRuntimeIssue,
  sanitizeSupportUrl,
  serializeSupportDiagnosticsPayload,
} from "@/lib/support-diagnostics";

describe("formatSupportIssueSubmissionError", () => {
  it("turns nginx 413 html into a concise user-facing message", () => {
    const html = `<html><head><title>413 Request Entity Too Large</title></head><body><center><h1>413 Request Entity Too Large</h1></center></body></html>`;
    expect(formatSupportIssueSubmissionError(html)).toBe(
      "The attached screenshot or diagnostics were too large to upload. Please try again."
    );
  });

  it("maps CloudFront and auth failures to clean support messages", () => {
    const edgeText = "ERROR: The request could not be satisfied. Request blocked. Generated by cloudfront";

    expect(formatSupportIssueSubmissionError(edgeText)).toBe(
      "We could not submit the report right now. Please try again or contact support."
    );
    expect(formatSupportIssueSubmissionError(edgeText, { status: 403 })).toBe(
      "We could not submit the report right now. Please try again or contact support."
    );
    expect(formatSupportIssueSubmissionError("Forbidden", { status: 403 })).toBe(
      "Your session is not authorised for this action. Please refresh and sign in again."
    );
    expect(formatSupportIssueSubmissionError("rate limit", { status: 429 })).toBe(
      "Too many reports. Please wait and try again."
    );
  });

  it("strips markup and truncates noisy payloads", () => {
    const message = `<div><strong>Backend failed</strong><p>${"a".repeat(260)}</p></div>`;
    const formatted = formatSupportIssueSubmissionError(message);

    expect(formatted.startsWith("Backend failed aaaaa")).toBe(true);
    expect(formatted.endsWith("...")).toBe(true);
    expect(formatted.length).toBeLessThanOrEqual(220);
  });
});

describe("support diagnostics redaction", () => {
  it("redacts sensitive URL parameters before diagnostics are submitted", () => {
    expect(
      sanitizeSupportUrl(
        "https://app.example.test/dashboard?inviteToken=secret-token&sessionId=session-1&page=2#private",
        true
      )
    ).toBe("https://app.example.test/dashboard?inviteToken=%5Bredacted%5D&sessionId=%5Bredacted%5D&page=2#[redacted]");
  });

  it("builds bounded redacted support diagnostics", () => {
    window.history.pushState({}, "", "/history?inviteToken=secret-token&page=2");
    recordSupportNetworkLog({
      method: "POST",
      endpoint: "/api/support/reports?jwt=secret-jwt&page=2",
      status: 403,
      ok: false,
      durationMs: 30,
      error: "Authorization: Bearer eyJaaaaaaaabbbbbbbbbb.ccccccccccdddddddddd.eeeeeeeeeeffffffffff",
    });
    reportSupportRuntimeIssue({
      source: "runtime",
      message: "Failed with token=secret-token",
      stack: "Cookie: session=secret-session",
    });

    const payload = buildSupportDiagnosticsPayload();
    const serialized = serializeSupportDiagnosticsPayload(payload);

    expect(serialized.length).toBeLessThanOrEqual(120 * 1024);
    expect(serialized).not.toContain("secret-token");
    expect(serialized).not.toContain("secret-session");
    expect(serialized).not.toContain("Bearer eyJ");
    expect(getSanitizedSupportPageUrl()).toContain("inviteToken=%5Bredacted%5D");
  });
});
