DROP POLICY IF EXISTS printing_lifecycle_actionidempotencykey_insert ON public."ActionIdempotencyKey";
DROP POLICY IF EXISTS printing_lifecycle_actionidempotencykey_select ON public."ActionIdempotencyKey";
DROP POLICY IF EXISTS printing_lifecycle_actionidempotencykey_update ON public."ActionIdempotencyKey";
DROP POLICY IF EXISTS printing_lifecycle_auditlog_insert ON public."AuditLog";
DROP POLICY IF EXISTS printing_lifecycle_batch_select ON public."Batch";
DROP POLICY IF EXISTS printing_lifecycle_batch_update ON public."Batch";
DROP POLICY IF EXISTS printing_lifecycle_licensee_select ON public."Licensee";
DROP POLICY IF EXISTS printing_lifecycle_manufacturerlicenseelink_select ON public."ManufacturerLicenseeLink";
DROP POLICY IF EXISTS printing_lifecycle_organization_select ON public."Organization";
DROP POLICY IF EXISTS printing_lifecycle_printauditevent_insert ON public."PrintAuditEvent";
DROP POLICY IF EXISTS printing_lifecycle_printauditevent_select ON public."PrintAuditEvent";
DROP POLICY IF EXISTS printing_lifecycle_printer_delete ON public."Printer";
DROP POLICY IF EXISTS printing_lifecycle_printer_insert ON public."Printer";
DROP POLICY IF EXISTS printing_lifecycle_printer_select ON public."Printer";
DROP POLICY IF EXISTS printing_lifecycle_printer_update ON public."Printer";
DROP POLICY IF EXISTS printing_lifecycle_printerattestation_insert ON public."PrinterAttestation";
DROP POLICY IF EXISTS printing_lifecycle_printerattestation_select ON public."PrinterAttestation";
DROP POLICY IF EXISTS printing_lifecycle_printerregistration_insert ON public."PrinterRegistration";
DROP POLICY IF EXISTS printing_lifecycle_printerregistration_select ON public."PrinterRegistration";
DROP POLICY IF EXISTS printing_lifecycle_printerregistration_update ON public."PrinterRegistration";
DROP POLICY IF EXISTS printing_lifecycle_printitem_insert ON public."PrintItem";
DROP POLICY IF EXISTS printing_lifecycle_printitem_select ON public."PrintItem";
DROP POLICY IF EXISTS printing_lifecycle_printitem_update ON public."PrintItem";
DROP POLICY IF EXISTS printing_lifecycle_printitemevent_insert ON public."PrintItemEvent";
DROP POLICY IF EXISTS printing_lifecycle_printjob_insert ON public."PrintJob";
DROP POLICY IF EXISTS printing_lifecycle_printjob_select ON public."PrintJob";
DROP POLICY IF EXISTS printing_lifecycle_printjob_update ON public."PrintJob";
DROP POLICY IF EXISTS printing_lifecycle_printreissuerequest_insert ON public."PrintReissueRequest";
DROP POLICY IF EXISTS printing_lifecycle_printreissuerequest_select ON public."PrintReissueRequest";
DROP POLICY IF EXISTS printing_lifecycle_printreissuerequest_update ON public."PrintReissueRequest";
DROP POLICY IF EXISTS printing_lifecycle_printsession_insert ON public."PrintSession";
DROP POLICY IF EXISTS printing_lifecycle_printsession_select ON public."PrintSession";
DROP POLICY IF EXISTS printing_lifecycle_printsession_update ON public."PrintSession";
DROP POLICY IF EXISTS printing_lifecycle_qrcode_select ON public."QRCode";
DROP POLICY IF EXISTS printing_lifecycle_qrcode_update ON public."QRCode";
DROP POLICY IF EXISTS printing_lifecycle_securityeventoutbox_insert ON public."SecurityEventOutbox";
DROP POLICY IF EXISTS printing_lifecycle_sensitiveactionapproval_insert ON public."SensitiveActionApproval";
DROP POLICY IF EXISTS printing_lifecycle_sensitiveactionapproval_select ON public."SensitiveActionApproval";
DROP POLICY IF EXISTS printing_lifecycle_sensitiveactionapproval_update ON public."SensitiveActionApproval";
DROP POLICY IF EXISTS printing_lifecycle_user_select ON public."User";

REVOKE ALL ON FUNCTION app_rls.printing_create_job(text,text,text,text,text,integer,text,text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_readiness(text,text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_control_job(text,text,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_printer_administration(text,text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_idempotency(text,text,text,text,text,text,text,integer,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_connector_registration(text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_connector_event(text,text,text,text,timestamp without time zone,text,text,text,text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_connector_identity(text,text,text,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_test_label_job(text,text,text,text,jsonb,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_gateway_job(text,text,text,text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_record_sample(text,text,text,text,text,jsonb) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_release_batch(text,text,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_reissue_request(text,text,text,text,text,text,integer,text,text,text,text) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_worker_reconcile(text,text,integer) FROM PUBLIC;
REVOKE ALL ON FUNCTION app_rls.printing_worker_network_job(text,text,text,jsonb) FROM PUBLIC;

DROP FUNCTION IF EXISTS app_rls.printing_worker_reconcile(text,text,integer);
DROP FUNCTION IF EXISTS app_rls.printing_worker_network_job(text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_reissue_request(text,text,text,text,text,text,integer,text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.printing_release_batch(text,text,text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.printing_record_sample(text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_connector_event(text,text,text,text,timestamp without time zone,text,text,text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_connector_identity(text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.printing_test_label_job(text,text,text,text,jsonb,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_gateway_job(text,text,text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_control_job(text,text,text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.printing_printer_administration(text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_idempotency(text,text,text,text,text,text,text,integer,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_connector_registration(text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_create_job(text,text,text,text,text,integer,text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_readiness(text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_write_audit(text,text,text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.printing_bind_actor(text,text,text,text);
