export type HelpKbRole = "all" | "super_admin" | "licensee" | "manufacturer" | "customer";

export type HelpKbEntry = {
  id: string;
  role: HelpKbRole;
  keywords: string[];
  title: string;
  answer: string;
  linksToRoutes: string[];
};

export const HELP_KB: HelpKbEntry[] = [
  {
    id: "access-super-admin",
    role: "super_admin",
    keywords: ["access", "super admin", "login", "platform", "invitation"],
    title: "Getting access as Super Admin",
    answer: [
      "Super Admin accounts are platform-level accounts created by platform setup or another Super Admin.",
      "",
      "1. Open the sign-in page and use your admin email and password.",
      "2. If your account was invite-based, use the invite link first and set your password.",
      "3. After login, open **Licensees**, **QR Requests**, and **IR Center** from the left navigation.",
      "",
      "If sign-in fails, use **Forgot password**. If your account is disabled, contact another active Super Admin.",
    ].join("\n"),
    linksToRoutes: ["/login", "/help/super-admin", "/help/getting-access"],
  },
  {
    id: "access-licensee-admin",
    role: "licensee",
    keywords: ["access", "licensee", "admin", "invite", "brand account", "company account"],
    title: "Getting access as Licensee/Admin",
    answer: [
      "Licensee/Admin users are invited by Super Admin into a specific organization.",
      "",
      "1. Open the invite email and click **Activate account**.",
      "2. Set your password on the invite acceptance page.",
      "3. Sign in and confirm you can see your own licensee scope only.",
      "",
      "Licensee/Admin can request QR inventory, assign batches, manage manufacturers, and review tracking data.",
    ].join("\n"),
    linksToRoutes: ["/accept-invite", "/login", "/help/licensee-admin", "/help/getting-access"],
  },
  {
    id: "access-manufacturer",
    role: "manufacturer",
    keywords: ["access", "manufacturer", "factory", "invite", "factory user"],
    title: "Getting access as Manufacturer",
    answer: [
      "Manufacturer users are created or invited under a licensee and can only work with assigned batches.",
      "",
      "1. Use the invite or credentials shared by your Licensee/Admin.",
      "2. Sign in and open **Batches**.",
      "3. Use **Create Print Job** for assigned inventory only.",
      "",
      "If no batches are visible, ask your Licensee/Admin to assign a batch to your factory account.",
    ].join("\n"),
    linksToRoutes: ["/login", "/batches", "/help/manufacturer", "/help/getting-access"],
  },
  {
    id: "password-first-login",
    role: "all",
    keywords: ["password", "first login", "set password", "invite link", "activate account"],
    title: "Set password on first login (invite flow)",
    answer: [
      "First-time users set a password from the invite link.",
      "",
      "1. Open the invite link.",
      "2. Enter and confirm your new password.",
      "3. Submit and continue to dashboard.",
      "",
      "Invite links are one-time and time-limited. Request a fresh invite if the link has expired.",
    ].join("\n"),
    linksToRoutes: ["/accept-invite", "/help/setting-password"],
  },
  {
    id: "password-reset",
    role: "all",
    keywords: ["forgot password", "reset password", "password recovery", "cannot login"],
    title: "Reset password (forgot password flow)",
    answer: [
      "If you cannot sign in, use the reset flow.",
      "",
      "1. Open **Forgot password** and submit your account email.",
      "2. Open the reset link sent to your inbox.",
      "3. Set a new password and sign in again.",
      "",
      "If no email arrives, check spam and ask your admin to verify your account is active.",
    ].join("\n"),
    linksToRoutes: ["/forgot-password", "/reset-password", "/help/setting-password"],
  },
  {
    id: "qr-requests-workflow",
    role: "licensee",
    keywords: ["qr request", "request inventory", "approve", "reject", "quantity", "allocation"],
    title: "QR Requests workflow",
    answer: [
      "Licensee/Admin submits quantity requests. Super Admin approves or rejects.",
      "",
      "1. Licensee/Admin opens **QR Requests** and submits quantity.",
      "2. Super Admin reviews pending requests.",
      "3. On approval, the next available code range is allocated automatically.",
      "",
      "Use decision notes for audit clarity when approving or rejecting.",
    ].join("\n"),
    linksToRoutes: ["/qr-requests", "/help/licensee-admin", "/help/super-admin"],
  },
  {
    id: "batches-assign-manufacturer",
    role: "licensee",
    keywords: ["batch", "assign manufacturer", "remaining codes", "factory assignment"],
    title: "Assigning batches to manufacturers",
    answer: [
      "Licensee/Admin assigns received batches to manufacturer accounts.",
      "",
      "1. Open **Batches**.",
      "2. Pick a received batch and open **Assign Manufacturer**.",
      "3. Select manufacturer and quantity/range, then confirm.",
      "",
      "The manufacturer can only print assigned quantity after assignment.",
    ].join("\n"),
    linksToRoutes: ["/batches", "/help/licensee-admin"],
  },
  {
    id: "manufacturers-manage",
    role: "licensee",
    keywords: ["manufacturer", "create factory user", "factory account", "deactivate"],
    title: "Managing manufacturers",
    answer: [
      "Licensee/Admin manages factory accounts from **Manufacturers**.",
      "",
      "1. Open **Manufacturers** and click **Add Manufacturer**.",
      "2. Enter profile and login details.",
      "3. Save, then assign batches so the factory can print.",
      "",
      "Deactivate users when a factory should no longer print for your brand.",
    ].join("\n"),
    linksToRoutes: ["/manufacturers", "/help/licensee-admin", "/help/manufacturer"],
  },
  {
    id: "manufacturer-print-pack",
    role: "manufacturer",
    keywords: ["print job", "download zip", "print pack", "printed status", "factory"],
    title: "Manufacturer print pack flow",
    answer: [
      "Manufacturer users handle print execution only.",
      "",
      "1. Open **Batches** and click **Create Print Job** on an assigned batch.",
      "2. Enter quantity and generate job.",
      "3. Download secure ZIP and complete printing.",
      "",
      "After workflow confirmation, print status updates for tracking and audit.",
    ].join("\n"),
    linksToRoutes: ["/batches", "/help/manufacturer"],
  },
  {
    id: "tracking-page",
    role: "all",
    keywords: ["tracking", "scan history", "blocked", "first scans", "events", "timeline"],
    title: "Using QR Tracking",
    answer: [
      "The tracking page summarizes scan activity and lifecycle health.",
      "",
      "1. Filter by code, batch, status, date range, and scope.",
      "2. Review blocked and first-scan counts.",
      "3. Investigate unusual patterns before taking action.",
      "",
      "Super Admin sees platform-wide scope. Org roles see scoped data only.",
    ].join("\n"),
    linksToRoutes: ["/qr-tracking", "/help/roles-permissions"],
  },
  {
    id: "customer-verified-again",
    role: "customer",
    keywords: ["verified again", "repeat scan", "same customer", "already scanned"],
    title: "Why am I seeing Verified Again?",
    answer: [
      "**Verified Again** means the code is still authentic, and this is a repeat check.",
      "",
      "Typical reasons:",
      "- You scanned the same product again on your device.",
      "- You re-opened verification to show proof to someone.",
      "- You verified earlier and checked once more later.",
      "",
      "Use **Show details** to review scan timing and summary.",
    ].join("\n"),
    linksToRoutes: ["/verify", "/help/customer"],
  },
  {
    id: "customer-duplicate-explainer",
    role: "customer",
    keywords: ["possible duplicate", "duplicate", "fraud risk", "different device", "multiple scans", "counterfeit"],
    title: "How does duplication happen?",
    answer: [
      "**Possible Duplicate** appears when scan signals look unusual.",
      "",
      "Common triggers:",
      "- The same code is scanned from multiple devices in a short window.",
      "- There are many scans in a burst pattern.",
      "- Location/country pattern changes too quickly.",
      "",
      "What to do next:",
      "1. Use **Report suspected counterfeit**.",
      "2. Keep purchase proof/photo if available.",
      "3. Contact brand support from the verify page.",
    ].join("\n"),
    linksToRoutes: ["/verify", "/help/customer"],
  },
  {
    id: "customer-fraud-report",
    role: "customer",
    keywords: ["fraud report", "counterfeit", "report issue", "upload photo", "incident form"],
    title: "How to submit a fraud report",
    answer: [
      "You can report suspicious products directly from the verification result page.",
      "",
      "1. Select **Report suspected counterfeit**.",
      "2. Pick issue type and describe what you observed.",
      "3. Optionally add purchase details, email, and photos.",
      "4. Submit to create an incident reference.",
      "",
      "Scan metadata is auto-attached to speed up investigation.",
    ].join("\n"),
    linksToRoutes: ["/verify", "/help/customer"],
  },
  {
    id: "error-incident-email-sender-config",
    role: "super_admin",
    keywords: ["email from", "EMAIL_FROM", "sender not configured", "incident email"],
    title: "Error: Incident sender is not configured",
    answer: [
      "Incident email delivery requires SMTP credentials and a valid sender identity.",
      "",
      "Configuration checklist:",
      "1. Confirm SMTP credentials are set in server environment variables.",
      "2. Ensure the sender domain is allowed by your email provider.",
      "3. Retry the message from the incident timeline after configuration changes.",
      "",
      "If your provider rejects the From address, the system records the reason in timeline/audit logs for troubleshooting.",
    ].join("\n"),
    linksToRoutes: ["/account", "/ir", "/help/communications"],
  },
  {
    id: "error-email-delivery-failed",
    role: "all",
    keywords: ["delivery false", "email failed", "notification failed", "incident communication"],
    title: "Error: Email delivery failed",
    answer: [
      "If delivery shows failed, the incident timeline keeps the failure reason.",
      "",
      "Check these points:",
      "1. Recipient address is valid.",
      "2. SMTP/provider credentials are active.",
      "3. Sender domain/policy is allowed by your mail provider.",
      "",
      "You can retry from the incident communication panel after fixing config.",
    ].join("\n"),
    linksToRoutes: ["/incidents", "/help/communications"],
  },
  {
    id: "compliance-mandatory-statements",
    role: "all",
    keywords: [
      "uk gdpr",
      "data protection act 2018",
      "security access control",
      "incident response process",
      "qr non duplication policy",
      "audit retention days",
      "acceptable use",
      "hosting disclaimer",
      "compliance statements",
    ],
    title: "Mandatory compliance statements",
    answer: [
      "All manuals and help docs include the following required compliance statements with deployment placeholders.",
      "",
      "1. UK GDPR & Data Protection: **{{APP_NAME}}** processes personal data under UK GDPR and Data Protection Act 2018. Contact: **{{DPO_EMAIL}}** or **{{SUPER_ADMIN_EMAIL}}**.",
      "2. Security & Access Control: role-based access (Super Admin, Licensee, Manufacturer), HTTPS encryption, secure password handling, and audit logging for critical actions.",
      "3. Incident Response & Fraud Reporting process: report intake -> review -> containment -> documentation -> resolution.",
      "4. QR Code Usage & Non-Duplication policy: all QR codes are unique, traceable, single-use where applicable, and must not be duplicated, altered, or reused.",
      "5. Audit Logging notice: admin actions, QR allocations, fraud reports, and login attempts are retained for **{{RETENTION_DAYS}}** days.",
      "6. Acceptable Use clause: unauthorized access, reverse engineering, fraud-report misuse, and interference with security are prohibited.",
      "7. Hosting & Disclaimer: hosted via **{{HOSTING_PROVIDER}}** with reasonable security controls and service provided on a best-effort basis.",
    ].join("\n"),
    linksToRoutes: ["/help", "/help/auth-overview"],
  },
];
