import { HELP_COMPLIANCE_COPY, HELP_SITE_CONFIG } from "@/help/site-config";

export type HelpKbRole = "all" | "super_admin" | "licensee" | "manufacturer" | "customer";

export type HelpKbEntry = {
  id: string;
  role: HelpKbRole;
  keywords: string[];
  title: string;
  answer: string;
  linksToRoutes: string[];
};

export const HELP_KB: HelpKbEntry[] = [
  {
    id: "access-super-admin",
    role: "super_admin",
    keywords: ["access", "super admin", "login", "platform", "invitation"],
    title: "Getting access as Super Admin",
    answer: [
      "Super Admin accounts are platform-level accounts created by platform setup or another Super Admin.",
      "",
      "1. Open the sign-in page and use your admin email and password.",
      "2. If your account was invite-based, use the invite link first and set your password.",
      "3. After login, open **Licensees**, **QR Requests**, and **IR Center** from the left navigation.",
      "",
      "If sign-in fails, use **Forgot password**. If your account is disabled, contact another active Super Admin.",
    ].join("\n"),
    linksToRoutes: ["/login", "/help/super-admin", "/help/getting-access"],
  },
  {
    id: "access-licensee-admin",
    role: "licensee",
    keywords: ["access", "licensee", "admin", "invite", "brand account", "company account"],
    title: "Getting access as Licensee/Admin",
    answer: [
      "Licensee/Admin users are invited by Super Admin into a specific organization.",
      "",
      "1. Open the invite email and click **Activate account**.",
      "2. Set your password on the invite acceptance page.",
      "3. Sign in and confirm you can see your own licensee scope only.",
      "",
      "Licensee/Admin can request QR inventory, assign batches, manage manufacturers, and review tracking data.",
    ].join("\n"),
    linksToRoutes: ["/accept-invite", "/login", "/help/licensee-admin", "/help/getting-access"],
  },
  {
    id: "access-manufacturer",
    role: "manufacturer",
    keywords: ["access", "manufacturer", "factory", "invite", "factory user"],
    title: "Getting access as Manufacturer",
    answer: [
      "Manufacturer users are created or invited under a licensee and can only work with assigned batches.",
      "",
      "1. Use the invite or credentials shared by your Licensee/Admin.",
      "2. Sign in and open **Batches**.",
      "3. Use **Create Print Job** for assigned inventory only.",
      "",
      "If no batches are visible, ask your Licensee/Admin to assign a batch to your factory account.",
    ].join("\n"),
    linksToRoutes: ["/login", "/batches", "/help/manufacturer", "/help/getting-access"],
  },
  {
    id: "password-first-login",
    role: "all",
    keywords: ["password", "first login", "set password", "invite link", "activate account"],
    title: "Set password on first login (invite flow)",
    answer: [
      "First-time users set a password from the invite link.",
      "",
      "1. Open the invite link.",
      "2. Enter and confirm your new password.",
      "3. Submit and continue to dashboard.",
      "",
      "Invite links are one-time and time-limited. Request a fresh invite if the link has expired.",
    ].join("\n"),
    linksToRoutes: ["/accept-invite", "/help/setting-password"],
  },
  {
    id: "password-reset",
    role: "all",
    keywords: ["forgot password", "reset password", "password recovery", "cannot login"],
    title: "Reset password (forgot password flow)",
    answer: [
      "If you cannot sign in, use the reset flow.",
      "",
      "1. Open **Forgot password** and submit your account email.",
      "2. Open the reset link sent to your inbox.",
      "3. Set a new password and sign in again.",
      "",
      "If no email arrives, check spam and ask your admin to verify your account is active.",
    ].join("\n"),
    linksToRoutes: ["/forgot-password", "/reset-password", "/help/setting-password"],
  },
  {
    id: "qr-requests-workflow",
    role: "licensee",
    keywords: ["qr request", "request inventory", "approve", "reject", "quantity", "allocation"],
    title: "QR Requests workflow",
    answer: [
      "Licensee/Admin submits quantity requests. Super Admin approves or rejects.",
      "",
      "1. Licensee/Admin opens **QR Requests** and submits quantity.",
      "2. Super Admin reviews pending requests.",
      "3. On approval, the next available code range is allocated automatically.",
      "",
      "Use decision notes for audit clarity when approving or rejecting.",
    ].join("\n"),
    linksToRoutes: ["/qr-requests", "/help/licensee-admin", "/help/super-admin"],
  },
  {
    id: "batches-assign-manufacturer",
    role: "licensee",
    keywords: ["batch", "assign manufacturer", "remaining codes", "factory assignment", "workspace", "source batch"],
    title: "Assigning batches to manufacturers",
    answer: [
      "Licensee/Admin works from a stable source-batch workspace instead of managing split rows in the main list.",
      "",
      "1. Open **Batches**.",
      "2. Open the source batch row and select **Open** to enter the batch workspace.",
      "3. In the **Operations** tab, choose the manufacturer and allocation quantity, then confirm.",
      "4. Use **View allocation structure** to jump between the source batch and related manufacturer batches without leaving stacked dialogs open.",
      "5. Review manufacturer totals, remaining unassigned inventory, and merged audit history inside the same workspace dialog.",
      "",
      "The source batch remains the stable record. Only the allocated quantity becomes a manufacturer batch that can move into printing.",
    ].join("\n"),
    linksToRoutes: ["/batches", "/help/licensee-admin"],
  },
  {
    id: "manufacturers-manage",
    role: "licensee",
    keywords: ["manufacturer", "create factory user", "factory account", "deactivate", "pending printed", "view details"],
    title: "Managing manufacturers",
    answer: [
      "Licensee/Admin manages factory accounts from **Manufacturers**.",
      "",
      "1. Open **Manufacturers** and click **Add Manufacturer**.",
      "2. Enter profile and login details.",
      "3. Save, then use **View details**, **Pending**, or **Printed** to inspect that manufacturer's work.",
      "4. Open manufacturer batches directly from the manufacturer card or table row when you need to review assigned inventory.",
      "",
      "Deactivate users when a factory should no longer print for your brand.",
    ].join("\n"),
    linksToRoutes: ["/manufacturers", "/help/licensee-admin", "/help/manufacturer"],
  },
  {
    id: "manufacturer-print-pack",
    role: "manufacturer",
    keywords: ["print job", "direct print", "print agent", "render token", "printed status", "factory", "network direct", "network ipp", "printer profile"],
    title: "Manufacturer direct-print flow",
    answer: [
      "Manufacturer users handle print execution only, using a workstation connector, a registered raw LAN printer, or a registered IPP printer profile.",
      "",
      "1. Open **Batches** and click **Create Print Job** on an assigned batch.",
      "2. Select a registered printer profile and quantity.",
      "3. For **LOCAL_AGENT**, the workstation connector receives approved payloads only.",
      "4. For **NETWORK_DIRECT**, the backend dispatches directly to the registered raw label printer over LAN/IP.",
      "5. For **NETWORK_IPP**, MSCQR submits standards-based PDF jobs over IPP/IPPS either directly or through a site gateway.",
      "",
      "Supported network-direct languages today are **ZPL**, **TSPL**, **EPL**, and **CPCL**. Use **Printer Setup** for compatibility, readiness checks, and site connector setup.",
    ].join("\n"),
    linksToRoutes: ["/batches", "/printer-diagnostics", "/help/manufacturer"],
  },
  {
    id: "printer-compatibility",
    role: "manufacturer",
    keywords: ["printer compatibility", "wifi printer", "home printer", "industrial printer", "zpl", "tspl", "epl", "cpcl"],
    title: "Which printers are supported?",
    answer: [
      "MSCQR supports three production printing patterns.",
      "",
      "1. **LOCAL_AGENT**: best for USB, Wi-Fi, home, office, and workstation-managed industrial printers. The operating system must already see the printer and the workstation connector must be installed once and running in the background.",
      "2. **NETWORK_DIRECT**: best for controlled raw LAN printers registered by IP/port in MSCQR.",
      "3. **NETWORK_IPP**: best for AirPrint and IPP Everywhere devices that accept PDF jobs over IPP/IPPS, either backend-direct or through a site gateway.",
      "",
      `Current network-direct language support: ZPL, TSPL, EPL, and CPCL. SBPL, ESC/POS, and OTHER should use the local agent path today.`,
    ].join("\n"),
    linksToRoutes: ["/printer-diagnostics", "/help/manufacturer"],
  },
  {
    id: "tracking-page",
    role: "all",
    keywords: ["tracking", "scan history", "blocked", "first scans", "events", "timeline"],
    title: "Using QR Tracking",
    answer: [
      "The tracking page summarizes scan activity and lifecycle health using one shared filter model.",
      "",
      "1. Filter by code, batch ID or batch name, status, date range, and scope.",
      "2. Review totals, trend, and summary rows together before acting on a discrepancy.",
      "3. Open the allocation structure from the tracked batch when you need to understand how quantity was distributed.",
      "",
      "Super Admin sees platform-wide scope. Org roles see scoped data only.",
    ].join("\n"),
    linksToRoutes: ["/qr-tracking", "/help/roles-permissions"],
  },
  {
    id: "customer-verified-again",
    role: "customer",
    keywords: ["verified again", "repeat scan", "same customer", "already scanned"],
    title: "Why am I seeing Verified Again?",
    answer: [
      "**Verified Again** means the code is still authentic, and this is a repeat check.",
      "",
      "Typical reasons:",
      "- You scanned the same product again on your device.",
      "- You re-opened verification to show proof to someone.",
      "- You verified earlier and checked once more later.",
      "",
      "Use **Show details** to review scan timing and summary.",
    ].join("\n"),
    linksToRoutes: ["/verify", "/help/customer"],
  },
  {
    id: "customer-duplicate-explainer",
    role: "customer",
    keywords: ["possible duplicate", "duplicate", "fraud risk", "different device", "multiple scans", "counterfeit"],
    title: "How does duplication happen?",
    answer: [
      "**Possible Duplicate** appears when scan signals look unusual.",
      "",
      "Common triggers:",
      "- The same code is scanned from multiple devices in a short window.",
      "- There are many scans in a burst pattern.",
      "- Location/country pattern changes too quickly.",
      "",
      "What to do next:",
      "1. Use **Report suspected counterfeit**.",
      "2. Keep purchase proof/photo if available.",
      "3. Contact brand support from the verify page.",
    ].join("\n"),
    linksToRoutes: ["/verify", "/help/customer"],
  },
  {
    id: "customer-fraud-report",
    role: "customer",
    keywords: ["fraud report", "counterfeit", "report issue", "upload photo", "incident form"],
    title: "How to submit a fraud report",
    answer: [
      "You can report suspicious products directly from the verification result page.",
      "",
      "1. Select **Report suspected counterfeit**.",
      "2. Pick issue type and describe what you observed.",
      "3. Optionally add purchase details, email, and photos.",
      "4. Submit to create an incident reference.",
      "",
      "Scan metadata is auto-attached to speed up investigation.",
    ].join("\n"),
    linksToRoutes: ["/verify", "/help/customer"],
  },
  {
    id: "error-incident-email-sender-config",
    role: "super_admin",
    keywords: ["email from", "EMAIL_FROM", "sender not configured", "incident email"],
    title: "Error: Incident sender is not configured",
    answer: [
      "Incident email delivery requires SMTP credentials and a valid sender identity.",
      "",
      "Configuration checklist:",
      "1. Confirm SMTP credentials are set in server environment variables.",
      "2. Ensure the sender domain is allowed by your email provider.",
      "3. Retry the message from the incident timeline after configuration changes.",
      "",
      "If your provider rejects the From address, the system records the reason in timeline/audit logs for troubleshooting.",
    ].join("\n"),
    linksToRoutes: ["/account", "/ir", "/help/communications"],
  },
  {
    id: "error-email-delivery-failed",
    role: "all",
    keywords: ["delivery false", "email failed", "notification failed", "incident communication"],
    title: "Error: Email delivery failed",
    answer: [
      "If delivery shows failed, the incident timeline keeps the failure reason.",
      "",
      "Check these points:",
      "1. Recipient address is valid.",
      "2. SMTP/provider credentials are active.",
      "3. Sender domain/policy is allowed by your mail provider.",
      "",
      "You can retry from the incident communication panel after fixing config.",
    ].join("\n"),
    linksToRoutes: ["/help/communications"],
  },
  {
    id: "compliance-mandatory-statements",
    role: "all",
    keywords: [
      "uk gdpr",
      "data protection act 2018",
      "security access control",
      "incident response process",
      "qr non duplication policy",
      "audit retention days",
      "acceptable use",
      "hosting disclaimer",
      "compliance statements",
    ],
    title: "Mandatory compliance statements",
    answer: [
      "All manuals and help docs include the following active compliance statements for this deployment.",
      "",
      `1. UK GDPR & Data Protection: ${HELP_COMPLIANCE_COPY.ukGdpr}`,
      `2. Security & Access Control: ${HELP_COMPLIANCE_COPY.security}`,
      `3. Incident Response & Fraud Reporting process: ${HELP_COMPLIANCE_COPY.incidentResponse}`,
      `4. QR Code Usage & Non-Duplication policy: ${HELP_COMPLIANCE_COPY.qrUsage}`,
      `5. Audit Logging notice: ${HELP_COMPLIANCE_COPY.auditRetention}`,
      `6. Acceptable Use clause: ${HELP_COMPLIANCE_COPY.acceptableUse}`,
      `7. Hosting & Disclaimer: ${HELP_COMPLIANCE_COPY.hosting}`,
      "",
      `Deployment reference: ${HELP_SITE_CONFIG.appName}, ${HELP_SITE_CONFIG.dpoEmail}, ${HELP_SITE_CONFIG.superAdminEmail}, ${HELP_SITE_CONFIG.retentionDays} day retention, hosted on ${HELP_SITE_CONFIG.hostingProvider}.`,
    ].join("\n"),
    linksToRoutes: ["/help", "/help/auth-overview"],
  },
];
