DROP FUNCTION IF EXISTS app_rls.change_authenticated_password(text,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.update_authenticated_profile(text,boolean,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.request_authenticated_email_change(text,text,text,timestamp without time zone,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_rls.require_recent_sensitive_session(text,timestamp without time zone,integer,integer);
DROP FUNCTION IF EXISTS app_rls.prove_authenticated_password_step_up(text,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.revoke_all_refresh_tokens(text,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.list_active_refresh_tokens(text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.load_authenticated_password_actor();
DROP FUNCTION IF EXISTS app_rls.create_refresh_token(text,text,text,timestamp without time zone,text,text,timestamp without time zone,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.record_auth_session_risk_signal(integer,text,text[],text,text,timestamp without time zone,text,text,text,timestamp without time zone,integer,text);
DROP FUNCTION IF EXISTS app_rls.load_recent_auth_session_risk_inputs(integer);
DROP FUNCTION IF EXISTS app_rls.require_recent_mfa_session(text,timestamp without time zone,integer);
DROP FUNCTION IF EXISTS app_rls.disable_admin_mfa(timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_rls.complete_admin_mfa_challenge(text,text,text,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_rls.delete_admin_webauthn_credential(text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.complete_admin_webauthn_authentication(text,text,text,integer,integer,text,boolean,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.complete_admin_webauthn_registration(text,text,text,text,integer,text[],text,boolean,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.load_admin_webauthn_challenge(text[],text,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.create_admin_webauthn_challenge(text,text,text,text,text,text,text,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.load_admin_webauthn_credentials();
DROP FUNCTION IF EXISTS app_rls.record_admin_mfa_challenge_failure(text,text,text,integer,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_rls.load_admin_mfa_challenge(text[],text[],timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.create_admin_mfa_challenge(text,text,text,text,integer,text,text[],text,text,integer,timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.replace_admin_backup_codes(text[],timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.consume_admin_mfa_verifier(text,text,text[],text[],timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.load_admin_mfa_verifiers();
DROP FUNCTION IF EXISTS app_rls.complete_admin_totp_enrollment(text,text,text,text,text,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_rls.load_admin_totp_enrollment(text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.begin_admin_totp_enrollment(text,text,text,text,text[],timestamp without time zone,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.load_admin_mfa_state();
DROP FUNCTION IF EXISTS app_rls.b01_admin_mfa_actor();
DROP FUNCTION IF EXISTS app_rls.revoke_refresh_token_by_id(text,text,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.find_refresh_token_by_id(text,text);
DROP FUNCTION IF EXISTS app_rls.load_authenticated_actor();
DROP FUNCTION IF EXISTS app_rls.load_authenticated_manufacturer_scope(text,text,text,text,boolean);
DROP FUNCTION IF EXISTS app_rls.revalidate_authenticated_actor(text,text,text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b01_authenticated_actor(text,text,text);
