REVOKE ALL ON FUNCTION app_rls.b03_add_support_ticket_message(text,text,boolean,timestamp without time zone,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_update_support_ticket(text,text,text,boolean,timestamp without time zone,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_get_support_ticket(text,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_list_support_tickets(text,text,text,text,integer,integer,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_complete_incident_email_delivery(text,text,text,text,text,text,text,timestamp without time zone) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_claim_incident_email_delivery(text,text,text,text,text,text,text,text,text,text,text,text,text,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_resolve_incident_notification_scope(text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_mark_all_notifications_read(text,timestamp without time zone,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_attention_queue_projection(text,timestamp without time zone,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_mark_notification_read(text,text,timestamp without time zone,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_list_notifications_for_user(text,integer,integer,boolean,timestamp without time zone,text,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_mark_notification_emailed(text,timestamp without time zone,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_create_user_notification(text,text,text,text,text,text,text,jsonb,text,text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_create_role_notifications(text,text,text,text,text,text,text,jsonb,text[],text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_resolve_incident_email_actor(text) FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_superadmin_alert_emails() FROM {{APP_ROLE}};
REVOKE ALL ON FUNCTION app_rls.b03_primary_superadmin_email() FROM {{APP_ROLE}};
DROP FUNCTION IF EXISTS app_rls.b03_add_support_ticket_message(text,text,boolean,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b03_update_support_ticket(text,text,text,boolean,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b03_get_support_ticket(text,text);
DROP FUNCTION IF EXISTS app_rls.b03_list_support_tickets(text,text,text,text,integer,integer,text);
DROP FUNCTION IF EXISTS app_rls.b03_complete_incident_email_delivery(text,text,text,text,text,text,text,timestamp without time zone);
DROP FUNCTION IF EXISTS app_rls.b03_claim_incident_email_delivery(text,text,text,text,text,text,text,text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.b03_resolve_incident_notification_scope(text);
DROP FUNCTION IF EXISTS app_rls.b03_mark_all_notifications_read(text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b03_attention_queue_projection(text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b03_mark_notification_read(text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b03_list_notifications_for_user(text,integer,integer,boolean,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_rls.b03_mark_notification_emailed(text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_rls.b03_create_user_notification(text,text,text,text,text,text,text,jsonb,text,text);
DROP FUNCTION IF EXISTS app_rls.b03_create_role_notifications(text,text,text,text,text,text,text,jsonb,text[],text);
DROP FUNCTION IF EXISTS app_rls.b03_resolve_incident_email_actor(text);
DROP FUNCTION IF EXISTS app_rls.b03_superadmin_alert_emails();
DROP FUNCTION IF EXISTS app_rls.b03_primary_superadmin_email();
DROP FUNCTION IF EXISTS app_rls.b03_assert_requested_scope(text,text);
DROP FUNCTION IF EXISTS app_rls.b03_require_authenticated_actor(text);
REVOKE ALL ON FUNCTION app_rls.b03_authenticated_context_valid() FROM PUBLIC;
DROP FUNCTION IF EXISTS app_rls.b03_authenticated_context_valid();
