import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { compareProductionSecurityRebaseline } from "../aws/compare-production-security-rebaseline.mjs";
import { assertSemanticallyEmptyRlsProbeOverrides, authenticateCompleteRlsProbeObservation, buildProductionRlsProbeCommand, collectCompleteRlsProbeLogEvents, waitForCompleteRlsProbeObservation } from "../aws/probe-production-rls-catalogue.mjs";
import { APP_ONLY_VERIFIER } from "../aws/production-app-only-policy.mjs";
import { canonicalSha256 } from "../aws/production-green-stage-b-contract.mjs";
import { createLiveSecurityRebaselineInventory, createSecurityRebaselineInventory, diffSecurityRebaselineInventories, SECURITY_REBASELINE_OPERATIONS } from "../aws/production-security-rebaseline-inventory.mjs";
import { createSecurityCatalogueTransportKeyPair, decryptSecurityCatalogueTransport, encryptSecurityCatalogueTransport } from "../aws/production-security-rebaseline-transport.mjs";
import { writeStageBPrivateFileExclusive } from "../aws/stage-b-artifact-contract.mjs";

const root = process.cwd(), sourceSha = "a".repeat(40), digest = "b".repeat(64), role = "mscqr_prd_rls_phase2_app";
const grant = (privilege = "SELECT") => ({ role, privilege, grantable: false });
function catalogue() { const table = { name: "User", kind: "r", rls: true, forced: true, owner: "mscqr_prod_admin", columns: [{ name: "id", type: "text", notNull: true, identity: "", generated: "", default: null, enumLabels: [] }], constraints: [], grants: [grant()], column_grants: [{ column: "id", ...grant() }] }; const policy = { table: "User", name: "user_read", permissive: true, command: "r", roles: [role], using: "id = current_user", check: null }; return { identity: { role:"mscqr_prod_rls_canary_read",session_role:"mscqr_prod_rls_canary_read",database:"mscqr_production_rls_green_phase2",server_version_num:180004,read_only:"on",default_read_only:"on",rolsuper:false,rolinherit:false,rolcreaterole:false,rolcreatedb:false,rolreplication:false,rolbypassrls:false,memberships:false,write_privileges:false,schema_write:false,database_write:false },
  routines: [{ schema: "app_auth", name: "secure", arguments: "value text", result: "boolean", owner: "mscqr_prod_admin", security_definer: true, volatility: "s", parallel: "u", leakproof: false, strict: true, config: ["search_path=pg_catalog"], body: "SELECT true", language: "sql", definition: "CREATE FUNCTION app_auth.secure(value text) RETURNS boolean LANGUAGE sql AS 'SELECT true'", grants: [grant("EXECUTE")] }],
  securityRoutines: [{ schema: "app_auth", name: "secure", arguments: "value text", result: "boolean", owner: "mscqr_prod_admin", security_definer: true, volatility: "s", parallel: "u", leakproof: false, strict: true, config: ["search_path=pg_catalog"], body: "SELECT true", language: "sql", definition: "CREATE FUNCTION app_auth.secure(value text) RETURNS boolean LANGUAGE sql AS 'SELECT true'", grants: [grant("EXECUTE")] }],
  tables: [structuredClone(table)], securityTables: [{ schema:"public",...structuredClone(table) }],
  policies: [structuredClone(policy)], securityPolicies: [{ schema:"public",...structuredClone(policy) }],
  schemas: [{ name: "public", owner: "mscqr_prod_admin", grants: [] }, { name: "app_auth", owner: "mscqr_prod_admin", grants: [grant("USAGE")] }],
  securitySchemas: [{ name: "public", owner: "mscqr_prod_admin", grants: [] }, { name: "app_auth", owner: "mscqr_prod_admin", grants: [grant("USAGE")] }],
  roles: [{ name: role, login: false, superuser: false, inherit: false, create_role: false, create_database: false, replication: false, bypass_rls: false, memberships: [], members: [] }],
  roleMetadata: [{ name: role, comment_present: true, comment_sha256: digest, settings: [{ database: "*", settings: ["row_security=on"] }], unsupported_settings: false }, { name: "mscqr_prod_admin", comment_present: false, comment_sha256: digest, settings: [], unsupported_settings: false }],
  databases: [{ database: "mscqr_production_rls_green_phase2", owner: "mscqr_prod_admin", role, privilege: "CONNECT", grantable: false }],
  defaults: [{ owner: role, schema: "public", object_type: "r", role, privilege: "SELECT", grantable: false }],
  types: [{ schema: "public", name: "Status", kind: "e", owner: "mscqr_prod_admin", grants: [grant("USAGE")] }],
  sequences: [{ schema: "public", name: "example_seq", owner: "mscqr_prod_admin", grants: [grant("USAGE")] }],
  operatorCapabilities: [{ name: "mscqr_prod_admin", login: true, superuser: false, inherit: true, create_role: true, create_database: false, replication: false, bypass_rls: true, database_connect: true, database_create: false, database_temporary: false, memberships: [], membership_closure: [] }] }; }
const canonical = (value = catalogue()) => createSecurityRebaselineInventory({ kind: "CANONICAL", protectedMainSha: sourceSha, catalogue: value, repositoryRoot: root, packageChecksums: { fixture: digest } });
const live = (value, target = canonical()) => createLiveSecurityRebaselineInventory({ protectedMainSha: sourceSha, catalogue: value, canonical: target, taskEvidence: { taskArn: "arn:aws:ecs:eu-west-2:368992683803:task/mscqr-prod-euw2-main/" + "c".repeat(32), taskDefinitionArn: "arn:aws:ecs:eu-west-2:368992683803:task-definition/security-rebaseline:1", containerName: "production-green-read-only-rls-canary", containerExitCode: 0, requestSha256: digest, verificationContractSha256: digest } });

test("identical catalogues have a deterministic zero diff", () => { const target = canonical(), a = diffSecurityRebaselineInventories(live(catalogue(), target), target), reversed = catalogue(); for (const key of Object.keys(reversed)) if (Array.isArray(reversed[key])) reversed[key].reverse(); const b = diffSecurityRebaselineInventories(live(reversed, target), target); assert.equal(a.differenceCount, 0); assert.equal(a.artifactSha256, b.artifactSha256); });

for (const [label, mutate, expected] of [
  ["policy command", (c) => c.securityPolicies[0].command="a", "ALTER"], ["policy role", (c) => c.securityPolicies[0].roles=["PUBLIC"], "ALTER"], ["USING", (c) => c.securityPolicies[0].using="true", "ALTER"], ["WITH CHECK", (c) => c.securityPolicies[0].check="true", "ALTER"],
  ["RLS enabled", (c) => c.securityTables[0].rls=false, "ENABLE_RLS"], ["RLS forced", (c) => c.securityTables[0].forced=false, "FORCE_RLS"], ["role attribute", (c) => c.roles[0].login=true, "ROLE_CHANGE"], ["membership", (c) => c.roles[0].memberships=[{ role, admin:false, inherit:true, set:true }], "ROLE_CHANGE"],
  ["ownership", (c) => c.securityTables[0].owner="other", "OWNERSHIP_CHANGE"], ["schema ACL", (c) => c.securitySchemas[1].grants=[], "GRANT"], ["table ACL", (c) => c.securityTables[0].grants=[], "GRANT"], ["function ACL", (c) => c.securityRoutines[0].grants=[], "GRANT"], ["column ACL", (c) => c.securityTables[0].column_grants=[], "GRANT"],
  ["database ACL", (c) => c.databases=[], "GRANT"], ["default privilege", (c) => c.defaults=[], "GRANT"], ["type ACL", (c) => c.types[0].grants=[], "GRANT"], ["sequence ACL", (c) => c.sequences[0].grants=[], "GRANT"],
  ["managed role comment", (c) => c.roleMetadata[0].comment_sha256="d".repeat(64), "ROLE_CHANGE"], ["managed role setting", (c) => c.roleMetadata[0].settings=[], "ROLE_CHANGE"], ["operator capability", (c) => c.operatorCapabilities[0].bypass_rls=false, "ROLE_CHANGE"], ["function security", (c) => c.securityRoutines[0].security_definer=false, "ALTER"],
]) test(`${label} difference is categorized`, () => { const target=canonical(), value=catalogue(); mutate(value); assert.ok(diffSecurityRebaselineInventories(live(value,target),target).differences.some(({operation})=>operation===expected)); });

test("duplicate identities, unsupported fields and unexpected roles fail closed", () => { for (const mutate of [(c)=>c.securityPolicies.push(structuredClone(c.securityPolicies[0])), (c)=>c.securityPolicies[0].extra=true, (c)=>c.roles[0].name="attacker", (c)=>c.roleMetadata[0].unsupported_settings=true]) { const value=catalogue(); mutate(value); assert.throws(()=>canonical(value)); } });
test("unexpected business objects hard-stop and cannot become business DML or schema/table DROP", () => { const target=canonical(); for (const mutate of [(c)=>c.securityTables.push({...structuredClone(c.securityTables[0]),name:"Unexpected"}),(c)=>c.securitySchemas.push({name:"unexpected",owner:"mscqr_prod_admin",grants:[]}),(c)=>c.securityRoutines.push({...structuredClone(c.securityRoutines[0]),schema:"public",name:"unexpected"})]) { const value=catalogue(); mutate(value); const diff=diffSecurityRebaselineInventories(live(value,target),target); assert.equal(diff.safeToConstructConvergencePlan,false); assert.ok(diff.differences.some(({operation})=>operation==="UNEXPECTED_OBJECT")); } assert.ok(SECURITY_REBASELINE_OPERATIONS.every((value)=>!/(?:INSERT|UPDATE|DELETE|TRUNCATE|DROP_TABLE|DROP_SCHEMA)/.test(value))); });
test("unexpected direct and recursively inherited admin capabilities hard-stop", () => { const target=canonical(), value=catalogue(); value.operatorCapabilities[0].memberships=[{role:"intermediate_writer",admin:false,inherit:true,set:true}]; value.operatorCapabilities[0].membership_closure=["intermediate_writer","pg_write_all_data"]; assert.throws(()=>canonical(value),/non-allowlisted role grant or membership/); const diff=diffSecurityRebaselineInventories(live(value,target),target); assert.equal(diff.safeToConstructConvergencePlan,false); assert.ok(diff.differences.some(({collection})=>collection==="operatorMemberships")); assert.ok(diff.differences.some(({collection})=>collection==="operatorInheritedCapabilities")); });
test("source-contract, migration and PostgreSQL major mismatches fail closed", () => { const target=canonical(), observed=live(catalogue(),target); for (const field of ["sourceContractSha256","migrationSetDigest","collectorVersion"]) { const changed=structuredClone(observed); changed[field]=field==="collectorVersion"?"wrong":digest; changed.artifactSha256=crypto.createHash("sha256").update(JSON.stringify(changed)).digest("hex"); assert.throws(()=>diffSecurityRebaselineInventories(changed,target)); } const value=catalogue(); value.identity.server_version_num=170000; assert.throws(()=>canonical(value)); });
test("secret-shaped fields and values cannot enter artifacts", () => { const value=catalogue(); value.securityPolicies[0][["pass","word"].join("")]="forbidden"; assert.throws(()=>canonical(value)); value.securityPolicies[0]=catalogue().securityPolicies[0]; value.securityPolicies[0].using=["postgresql","://name:value@example"].join(""); assert.throws(()=>canonical(value)); });

test("encrypted catalogue transport is complete, private and substitution-resistant", () => { const keys=createSecurityCatalogueTransportKeyPair(), binding={sourceSha,requirementsSha256:digest}, value={catalogue:catalogue(),padding:crypto.randomBytes(300000).toString("hex")}, chunks=encryptSecurityCatalogueTransport(value,keys.publicKeyPem,binding); assert.deepEqual(decryptSecurityCatalogueTransport(chunks,keys.privateKeyPem,binding),value); assert.ok(!chunks.join("").includes("app_auth")); assert.throws(()=>decryptSecurityCatalogueTransport(chunks.slice(1),keys.privateKeyPem,binding)); assert.throws(()=>decryptSecurityCatalogueTransport([...chunks,chunks[0]],keys.privateKeyPem,binding)); });
test("fixed task command carries only the ephemeral public transport key within ECS limits", () => { const keys=createSecurityCatalogueTransportKeyPair(), command=buildProductionRlsProbeCommand({requirementsSha256:digest},{sourceSha,databaseHostname:"example.invalid"},{securityTransportPublicKey:keys.publicKeyPem}); assert.ok(Buffer.byteLength(command[1])<=48000); assert.ok(command[1].includes("BEGIN PUBLIC KEY")); assert.ok(!command[1].includes("BEGIN PRIVATE KEY")); });
test("fixed launch normalization accepts only observed inert overrides", () => { assert.equal(assertSemanticallyEmptyRlsProbeOverrides({containerOverrides:[{name:"production-green-read-only-rls-canary"}],inferenceAcceleratorOverrides:[]},"production-green-read-only-rls-canary"),true); for (const value of [{containerOverrides:[{name:"wrong"}],inferenceAcceleratorOverrides:[]},{containerOverrides:[{name:"production-green-read-only-rls-canary",command:["true"]}],inferenceAcceleratorOverrides:[]},{containerOverrides:[{name:"production-green-read-only-rls-canary"}],inferenceAcceleratorOverrides:[{deviceName:"x",deviceType:"y"}]}]) assert.throws(()=>assertSemanticallyEmptyRlsProbeOverrides(value,"production-green-read-only-rls-canary")); });
test("log pagination handles empty and partial pages and fails closed", () => { assert.deepEqual(collectCompleteRlsProbeLogEvents([{events:[],requestToken:undefined,nextForwardToken:"a"},{events:[{message:"one"}],requestToken:"a",nextForwardToken:"b"},{events:[],requestToken:"b",nextForwardToken:"b"}]),["one"]); assert.throws(()=>collectCompleteRlsProbeLogEvents([{events:[],requestToken:undefined,nextForwardToken:"a"}])); });
test("CloudWatch completion waits for authenticated terminal evidence and every declared chunk", () => { const keys=createSecurityCatalogueTransportKeyPair(), binding={sourceSha,requirementsSha256:digest}, chunks=encryptSecurityCatalogueTransport({padding:crypto.randomBytes(300000).toString("hex")},keys.publicKeyPem,binding); assert.ok(chunks.length>1); const first=JSON.parse(chunks[0]), body={schemaVersion:1,kind:"PRODUCTION_RLS_CATALOGUE_PROBE",sourceSha,requirementsSha256:digest,databaseRole:APP_ONLY_VERIFIER.databaseRole,catalogue:{routines:[],tables:[],policies:[],schemas:[],roles:[]},securityTransport:{transportSha256:first.transportSha256,count:first.count}}, terminal=JSON.stringify({...body,evidenceSha256:canonicalSha256(body)}), options={sourceSha,requirementsSha256:digest,securityMode:true}; assert.equal(authenticateCompleteRlsProbeObservation([chunks[0]],options),null,"chunks alone wait"); assert.equal(authenticateCompleteRlsProbeObservation([terminal,...chunks.slice(0,-1)],options),null,"terminal before final chunk waits"); assert.equal(authenticateCompleteRlsProbeObservation([...chunks],options),null,"all chunks before terminal wait"); const complete=authenticateCompleteRlsProbeObservation([...chunks,terminal],options); assert.equal(complete.chunks.length,chunks.length); assert.throws(()=>authenticateCompleteRlsProbeObservation([...chunks,chunks[0],terminal],options)); assert.throws(()=>authenticateCompleteRlsProbeObservation([...chunks,terminal,terminal],options)); const forged=JSON.stringify({...JSON.parse(terminal),sourceSha:"f".repeat(40)}), mismatchedChunk=JSON.parse(chunks[0]); mismatchedChunk.transportSha256="0".repeat(64); assert.throws(()=>authenticateCompleteRlsProbeObservation([...chunks.slice(1),JSON.stringify(mismatchedChunk),terminal],options)); assert.throws(()=>authenticateCompleteRlsProbeObservation([...chunks,forged],options)); });
test("bounded CloudWatch polling succeeds after delayed ingestion and times out without relaunch", async () => { const keys=createSecurityCatalogueTransportKeyPair(), binding={sourceSha,requirementsSha256:digest,securityMode:true}, chunks=encryptSecurityCatalogueTransport({padding:crypto.randomBytes(300000).toString("hex")},keys.publicKeyPem,binding), first=JSON.parse(chunks[0]), body={schemaVersion:1,kind:"PRODUCTION_RLS_CATALOGUE_PROBE",sourceSha,requirementsSha256:digest,databaseRole:APP_ONLY_VERIFIER.databaseRole,catalogue:{routines:[],tables:[],policies:[],schemas:[],roles:[]},securityTransport:{transportSha256:first.transportSha256,count:first.count}}, terminal=JSON.stringify({...body,evidenceSha256:canonicalSha256(body)}); for (const snapshots of [[[chunks[0]],[...chunks],[...chunks,terminal]],[[...chunks],[...chunks,terminal]],[[terminal,...chunks.slice(0,-1)],[...chunks,terminal]]]) { let reads=0, waits=0; const result=await waitForCompleteRlsProbeObservation(async()=>snapshots[Math.min(reads++,snapshots.length-1)],binding,{attempts:5,wait:async(ms)=>{assert.equal(ms,5000);waits++;}}); assert.ok(result); assert.equal(reads,snapshots.length); assert.equal(waits,reads-1); } let reads=0, waits=0; assert.equal(await waitForCompleteRlsProbeObservation(async()=>{reads++;return [chunks[0]];},binding,{attempts:3,wait:async()=>{waits++;}}),null); assert.equal(reads,3); assert.equal(waits,2); });
test("private comparison writes mode 0600 and returns only bounded summary", () => { const directory=fs.mkdtempSync(path.join(os.tmpdir(),"rebaseline-test-")); try { const target=canonical(), observed=live(catalogue(),target), canonicalPath=path.join(directory,"canonical.json"),livePath=path.join(directory,"live.json"),outPath=path.join(directory,"diff.json"); writeStageBPrivateFileExclusive({filePath:canonicalPath,bytes:Buffer.from(JSON.stringify(target)),repositoryRoot:root}); writeStageBPrivateFileExclusive({filePath:livePath,bytes:Buffer.from(JSON.stringify(observed)),repositoryRoot:root}); const result=compareProductionSecurityRebaseline({sourceSha,livePath,canonicalPath,outPath,repositoryRoot:root,assertCheckout:()=>{}}); assert.equal(result.differenceCount,0); assert.equal(Object.hasOwn(result,"differences"),false); assert.equal(fs.statSync(outPath).mode&0o777,0o600); } finally { fs.rmSync(directory,{recursive:true,force:true}); } });
