import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { spawnSync } from "node:child_process";
import test from "node:test";
import { STAGING_DATABASE_ROLE_CONTEXT as C, assertDatabaseRoleOperatorIdentity } from "../lib/staging-database-role-credentials-core.mjs";
import { MUTATING_MODE_CONFIRMATIONS, createBrokerHandler, fixedRunTaskRequest, validateBrokerEvent } from "../../infra/terraform/staging-api/lambda/database-role-executor-broker/index.mjs";

const files = {
  trust: "documents/ops/iam/MSCQR_STAGING_DATABASE_ROLE_OPERATOR_TRUST_POLICY_2026-07-12.json",
  assume: "documents/ops/iam/MSCQR_STAGING_DATABASE_ROLE_OPERATOR_ASSUME_ROLE_POLICY_2026-07-12.json",
  role: "documents/ops/iam/MSCQR_STAGING_DATABASE_ROLE_OPERATOR_POLICY_2026-07-12.json",
};
const read = (file) => JSON.parse(fs.readFileSync(file, "utf8"));
const runCheck = (mutate = {}) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "mscqr-db-role-operator-iam-"));
  const env = { ...process.env };
  try {
    for (const [key, file] of Object.entries(files)) {
      const policy = read(file);
      mutate[key]?.(policy);
      const fixture = path.join(directory, `${key}.json`);
      fs.writeFileSync(fixture, JSON.stringify(policy), { mode: 0o600 });
      env[`MSCQR_STAGING_DATABASE_ROLE_OPERATOR_${key === "role" ? "POLICY" : key === "assume" ? "ASSUME_POLICY" : "TRUST_POLICY"}_PATH`] = fixture;
    }
    return spawnSync("node", ["scripts/check-staging-database-role-operator-iam.mjs"], { encoding: "utf8", env });
  } finally { fs.rmSync(directory, { recursive: true, force: true }); }
};
const output = (result) => `${result.stdout}\n${result.stderr}`;
const operatorIdentity = { Account: C.accountId, Arn: `arn:aws:sts::${C.accountId}:assumed-role/${C.operatorRole}/reviewed-session` };

test("reviewed database-role operator IAM templates pass", () => { const result = runCheck(); assert.equal(result.status, 0, output(result)); });
test("human operator has no RunTask PassRole or Secrets Manager access and reads only broker, RDS metadata, and helper logs", () => { const policy=read(files.role); const actions=policy.Statement.flatMap((statement)=>Array.isArray(statement.Action)?statement.Action:[statement.Action]); assert(!actions.includes("ecs:RunTask")); assert(!actions.includes("iam:PassRole")); assert(!actions.some((action)=>action.startsWith("secretsmanager:"))); for(const action of ["lambda:InvokeFunction","lambda:GetFunctionConfiguration"]){ const statement=policy.Statement.find((value)=>value.Action===action); assert.equal(statement.Resource,`arn:aws:lambda:${C.region}:${C.accountId}:function:${C.brokerFunction}:reviewed`); } const database=policy.Statement.find((statement)=>statement.Sid==="DiscoverOnlyReviewedStagingDatabaseMetadata"); assert.deepEqual(database,{Sid:"DiscoverOnlyReviewedStagingDatabaseMetadata",Effect:"Allow",Action:"rds:DescribeDBInstances",Resource:"*",Condition:{StringEquals:{"aws:RequestedRegion":C.region}}}); const logs=policy.Statement.find((statement)=>statement.Action==="logs:GetLogEvents"); assert.equal(logs.Resource,`arn:aws:logs:${C.region}:${C.accountId}:log-group:/ecs/mscqr-staging-backend:log-stream:database-role-admin/db-admin/*`); });
test("operator wildcard or production broker resources are rejected", async (t) => { for (const resource of ["*",`arn:aws:lambda:${C.region}:${C.accountId}:function:mscqr-production-database-role-executor-broker`]) await t.test(resource,()=>{ const result=runCheck({role:(policy)=>{policy.Statement.find((statement)=>statement.Action==="lambda:InvokeFunction").Resource=resource;}}); assert.notEqual(result.status,0); assert.match(output(result),/exact staging|production-looking/); }); });
test("trust rejects root wildcard and Terraform plan or apply principals", async (t) => { for (const principal of [`arn:aws:iam::${C.accountId}:root`, "*", `arn:aws:iam::${C.accountId}:role/mscqr-staging-terraform-plan-role`, `arn:aws:iam::${C.accountId}:role/mscqr-staging-terraform-apply-role`]) await t.test(principal, () => { const result = runCheck({ trust: (policy) => { policy.Statement[0].Principal.AWS = principal; } }); assert.notEqual(result.status, 0); assert.match(output(result), /Trust policy|forbidden/); }); });
test("trust requires MFA", () => { const result = runCheck({ trust: (policy) => { delete policy.Statement[0].Condition; } }); assert.notEqual(result.status, 0); assert.match(output(result), /require MFA/); });
test("only the dedicated assumed role can execute probe provision or verify", () => { assert.doesNotThrow(() => assertDatabaseRoleOperatorIdentity(operatorIdentity, { AWS_REGION: C.region })); for (const role of ["mscqr-staging-terraform-plan-role", "mscqr-staging-terraform-apply-role", "mscqr-staging-broad-operator"]) assert.throws(() => assertDatabaseRoleOperatorIdentity({ Account: C.accountId, Arn: `arn:aws:sts::${C.accountId}:assumed-role/${role}/session` }, { AWS_REGION: C.region }), /require assumed role/); });

const brokerConfig={clusterArn:`arn:aws:ecs:${C.region}:${C.accountId}:cluster/${C.cluster}`,taskDefinitionArn:`arn:aws:ecs:${C.region}:${C.accountId}:task-definition/mscqr-staging-database-role-admin:7`,subnets:["subnet-abc123","subnet-def456"],securityGroups:["sg-abc123"],executorContractSha256:"b".repeat(64),brokerSourceSha256:"a".repeat(64)};
test("broker accepts only reviewed credential and shared-RLS modes",()=>{ for(const mode of ["probe","verify","rls-shared-verify"]) assert.equal(validateBrokerEvent({mode}),mode); for(const [mode,confirmation] of Object.entries(MUTATING_MODE_CONFIRMATIONS)) assert.equal(validateBrokerEvent({mode,confirmation}),mode); for(const mode of ["cutover","rollback","",null]) assert.throws(()=>validateBrokerEvent({mode}),/outside the reviewed/); });
test("blue broker rejects every full-RLS mode",()=>{ for(const mode of ["full-rls-capability-preflight","full-rls-role-provision","full-rls-role-verify","full-rls-admin-bootstrap","full-rls-admin-ownership","full-rls-runtime-policy","full-rls-verification","full-rls-rollback"]) assert.throws(()=>validateBrokerEvent({mode}),/outside the reviewed/); });
test("every mutating broker mode requires its own exact non-generic confirmation",()=>{ assert.deepEqual(MUTATING_MODE_CONFIRMATIONS,{provision:"MSCQR_PROVISION_STAGING_DATABASE_ROLE_CREDENTIALS","rls-shared-apply":"MSCQR_APPLY_STAGING_RLS_SHARED_BATCH_PHASE","rls-shared-rollback":"MSCQR_ROLLBACK_STAGING_RLS_SHARED_BATCH_PHASE"}); for(const [mode,confirmation] of Object.entries(MUTATING_MODE_CONFIRMATIONS)){ assert.throws(()=>validateBrokerEvent({mode}),/unreviewed fields/); for(const wrong of ["YES","no",...Object.values(MUTATING_MODE_CONFIRMATIONS).filter((value)=>value!==confirmation)]) assert.throws(()=>validateBrokerEvent({mode,confirmation:wrong}),/exact confirmation/); assert.doesNotThrow(()=>fixedRunTaskRequest(mode,brokerConfig,confirmation)); } });
test("broker rejects extra fields and caller-controlled overrides",()=>{ for(const key of ["command","environment","networkConfiguration","taskDefinition","roles","count","launchType","platformVersion","tags","overrides"]) assert.throws(()=>validateBrokerEvent({mode:"probe",[key]:{}}),/unreviewed fields/); });
test("broker constructs one immutable Fargate request",()=>{ const request=fixedRunTaskRequest("verify",brokerConfig); assert.deepEqual(request,{cluster:brokerConfig.clusterArn,taskDefinition:brokerConfig.taskDefinitionArn,launchType:"FARGATE",count:1,networkConfiguration:{awsvpcConfiguration:{subnets:brokerConfig.subnets,securityGroups:brokerConfig.securityGroups,assignPublicIp:"DISABLED"}},overrides:{containerOverrides:[{name:"db-admin",environment:[{name:"MSCQR_VPC_EXECUTOR_MODE",value:"verify"}]}]}}); });
test("broker returns only sanitized checksum-bound task metadata",async()=>{ const taskArn=`arn:aws:ecs:${C.region}:${C.accountId}:task/${C.cluster}/fixture`; const handler=createBrokerHandler({config:brokerConfig,runTask:async()=>({tasks:[{taskArn}],failures:[]})}); assert.deepEqual(await handler({mode:"probe"}),{status:"started",taskArn,taskDefinitionArn:brokerConfig.taskDefinitionArn,executorContractSha256:brokerConfig.executorContractSha256,brokerSourceSha256:brokerConfig.brokerSourceSha256}); });
test("broker audit is bounded and contains no caller payload or resource identifiers",async()=>{ const records=[]; const taskArn=`arn:aws:ecs:${C.region}:${C.accountId}:task/${C.cluster}/fixture`; const handler=createBrokerHandler({config:brokerConfig,runTask:async()=>({tasks:[{taskArn}],failures:[]}),audit:(record)=>records.push(record)}); await handler({mode:"probe"},{awsRequestId:"request-fixture"}); assert.deepEqual(records,[{event:"database_role_executor_broker",outcome:"accepted",mode:"probe",reason:"validated",requestId:"request-fixture"},{event:"database_role_executor_broker",outcome:"started",mode:"probe",reason:"single-task",requestId:"request-fixture"}]); assert(!JSON.stringify(records).includes(taskArn)); });
test("broker rejects missing or malformed integrity bindings before task launch",async()=>{ for(const key of ["executorContractSha256","brokerSourceSha256"]){ let launches=0; const handler=createBrokerHandler({config:{...brokerConfig,[key]:"invalid"},runTask:async()=>{launches+=1;return{};}}); await assert.rejects(handler({mode:"probe"}),/immutable configuration/); assert.equal(launches,0); } });
test("broker Terraform role keeps RunTask and PassRole exact and secret-free",()=>{ const source=fs.readFileSync("infra/terraform/staging-api/main.tf","utf8"); const policy=source.match(/resource "aws_iam_role_policy" "database_role_executor_broker"[\s\S]*?(?=\nresource "aws_lambda_function")/)?.[0]||""; assert.match(policy,/task-definition\/mscqr-staging-database-role-admin:\*/); assert.match(policy,/ecs:cluster.*aws_ecs_cluster\.staging\.arn/); assert.match(policy,/aws_iam_role\.database_role_admin_task\.arn, aws_iam_role\.ecs_execution\.arn/); assert.match(policy,/iam:PassedToService.*ecs-tasks\.amazonaws\.com/); assert.doesNotMatch(policy,/Resource\s*=\s*"\*"|secretsmanager:GetSecretValue/); });
test("broker Terraform creates encrypted retained logs with scoped write-only permissions",()=>{ const source=fs.readFileSync("infra/terraform/staging-api/main.tf","utf8"); assert.match(source,/resource "aws_cloudwatch_log_group" "database_role_executor_broker"[\s\S]*retention_in_days = 30[\s\S]*kms_key_id/); assert.match(source,/Sid\s*= "WriteOnlyReviewedBrokerLogs"[\s\S]*logs:CreateLogStream[\s\S]*logs:PutLogEvents[\s\S]*database_role_executor_broker\.arn/); });
test("Terraform requires one exact digest-pinned image for backend and blue executor",()=>{ const variables=fs.readFileSync("infra/terraform/staging-api/variables.tf","utf8"); const source=fs.readFileSync("infra/terraform/staging-api/main.tf","utf8"); assert.match(variables,/mscqr-backend@sha256:\[a-f0-9\]\{64\}/); assert.equal((source.match(/image\s+= var\.backend_image_uri/g)||[]).length,2); });
test("credential controller never invokes ECS RunTask directly and sends the exact provision confirmation",()=>{ const source=fs.readFileSync("scripts/aws/staging-database-role-credentials.mjs","utf8"); assert.doesNotMatch(source,/\["ecs",\s*"run-task"/); assert.match(source,/\["lambda",\s*"invoke"/); assert.match(source,/PROVISION_BROKER_CONFIRMATION = "MSCQR_PROVISION_STAGING_DATABASE_ROLE_CREDENTIALS"/); assert.match(source,/mode === "provision" \? \{ confirmation: PROVISION_BROKER_CONFIRMATION \}/); });
