export {
  acceptOwnershipTransfer,
  beginCustomerPasskeyAssertion,
  beginCustomerPasskeyRegistration,
  cancelOwnershipTransfer,
  claimProductOwnership,
  createOwnershipTransfer,
  deleteCustomerPasskeyCredential,
  finishCustomerPasskeyAssertion,
  finishCustomerPasskeyRegistration,
  linkDeviceClaimToCustomer,
  listCustomerPasskeyCredentials,
  reportFraud,
  requestCustomerEmailOtp,
  submitProductFeedback,
  verifyCustomerEmailOtp,
  verifyQRCode,
} from "./verify/verifyHandlers";
