export {
  acceptOwnershipTransfer,
  beginCustomerPasskeyAssertion,
  beginCustomerPasskeyRegistration,
  cancelOwnershipTransfer,
  claimProductOwnership,
  completeCustomerOAuth,
  createOwnershipTransfer,
  deleteCustomerPasskeyCredential,
  exchangeCustomerOAuth,
  finishCustomerPasskeyAssertion,
  finishCustomerPasskeyRegistration,
  linkDeviceClaimToCustomer,
  listCustomerOAuthProviders,
  listCustomerPasskeyCredentials,
  logoutCustomerVerifySession,
  getCustomerVerificationSessionState,
  revealCustomerVerificationResult,
  reportFraud,
  requestCustomerEmailOtp,
  startCustomerOAuth,
  startCustomerVerificationSession,
  submitCustomerVerificationIntake,
  submitProductFeedback,
  verifyCustomerEmailOtp,
  verifyQRCode,
} from "./verify/verifyHandlers";
