DROP POLICY IF EXISTS public_verification_qrcode_select ON public."QRCode";
DROP POLICY IF EXISTS public_verification_qrcode_update ON public."QRCode";
DROP POLICY IF EXISTS public_verification_organization_select ON public."Organization";
DROP POLICY IF EXISTS public_verification_licensee_select ON public."Licensee";
DROP POLICY IF EXISTS public_verification_batch_select ON public."Batch";
DROP POLICY IF EXISTS public_verification_user_select ON public."User";
DROP POLICY IF EXISTS public_verification_replacementchain_select ON public."ReplacementChain";
DROP POLICY IF EXISTS public_verification_qrscanlog_select ON public."QrScanLog";
DROP POLICY IF EXISTS public_verification_qrscanlog_insert ON public."QrScanLog";
DROP POLICY IF EXISTS public_verification_verificationdecision_select ON public."VerificationDecision";
DROP POLICY IF EXISTS public_verification_verificationdecision_insert ON public."VerificationDecision";
DROP POLICY IF EXISTS public_verification_verificationevidencesnapshot_select ON public."VerificationEvidenceSnapshot";
DROP POLICY IF EXISTS public_verification_verificationevidencesnapshot_insert ON public."VerificationEvidenceSnapshot";
DROP POLICY IF EXISTS public_verification_verificationevidencesnapshot_update ON public."VerificationEvidenceSnapshot";
DROP POLICY IF EXISTS public_verification_customerverificationsession_select ON public."CustomerVerificationSession";
DROP POLICY IF EXISTS public_verification_customerverificationsession_insert ON public."CustomerVerificationSession";
DROP POLICY IF EXISTS public_verification_customerverificationsession_update ON public."CustomerVerificationSession";
DROP POLICY IF EXISTS public_verification_customertrustintake_select ON public."CustomerTrustIntake";
DROP POLICY IF EXISTS public_verification_customertrustintake_insert ON public."CustomerTrustIntake";
DROP POLICY IF EXISTS public_verification_customertrustintake_update ON public."CustomerTrustIntake";
DROP POLICY IF EXISTS public_verification_auditlog_insert ON public."AuditLog";
DROP POLICY IF EXISTS public_verification_securityeventoutbox_insert ON public."SecurityEventOutbox";
DROP POLICY IF EXISTS public_verification_actionidempotencykey_select ON public."ActionIdempotencyKey";
DROP POLICY IF EXISTS public_verification_actionidempotencykey_insert ON public."ActionIdempotencyKey";
DROP POLICY IF EXISTS public_verification_incident_insert ON public."Incident";
DROP POLICY IF EXISTS public_verification_incidentevent_insert ON public."IncidentEvent";
DROP POLICY IF EXISTS public_verification_incidentevidence_insert ON public."IncidentEvidence";
DROP POLICY IF EXISTS public_verification_supportticket_insert ON public."SupportTicket";
DROP POLICY IF EXISTS public_verification_supportticket_select ON public."SupportTicket";
DROP POLICY IF EXISTS public_verification_incidenthandoff_select ON public."IncidentHandoff";
DROP POLICY IF EXISTS public_verification_requestaccess_insert ON public."RequestAccess";
DROP POLICY IF EXISTS public_verification_requestaccess_select ON public."RequestAccess";
DROP POLICY IF EXISTS public_verification_requestaccess_update ON public."RequestAccess";
DROP POLICY IF EXISTS public_verification_supportissuereport_insert ON public."SupportIssueReport";
DROP POLICY IF EXISTS public_verification_supportissuereport_select ON public."SupportIssueReport";
DROP POLICY IF EXISTS public_verification_supportissuereport_update ON public."SupportIssueReport";
DROP POLICY IF EXISTS public_verification_customerauthsession_select ON public."CustomerAuthSession";
DROP POLICY IF EXISTS public_verification_customerauthsession_insert ON public."CustomerAuthSession";
DROP POLICY IF EXISTS public_verification_customerauthsession_update ON public."CustomerAuthSession";
DROP POLICY IF EXISTS public_verification_ownership_select ON public."Ownership";
DROP POLICY IF EXISTS public_verification_ownership_insert ON public."Ownership";
DROP POLICY IF EXISTS public_verification_ownership_update ON public."Ownership";
DROP POLICY IF EXISTS public_verification_ownershiptransfer_select ON public."OwnershipTransfer";
DROP POLICY IF EXISTS public_verification_ownershiptransfer_insert ON public."OwnershipTransfer";
DROP POLICY IF EXISTS public_verification_ownershiptransfer_update ON public."OwnershipTransfer";
DROP POLICY IF EXISTS public_verification_customerwebauthnchallenge_select ON public."CustomerWebAuthnChallenge";
DROP POLICY IF EXISTS public_verification_customerwebauthnchallenge_insert ON public."CustomerWebAuthnChallenge";
DROP POLICY IF EXISTS public_verification_customerwebauthnchallenge_update ON public."CustomerWebAuthnChallenge";
DROP POLICY IF EXISTS public_verification_customerwebauthncredential_select ON public."CustomerWebAuthnCredential";
DROP POLICY IF EXISTS public_verification_customerwebauthncredential_insert ON public."CustomerWebAuthnCredential";
DROP POLICY IF EXISTS public_verification_customerwebauthncredential_update ON public."CustomerWebAuthnCredential";
DROP POLICY IF EXISTS public_verification_customerwebauthncredential_delete ON public."CustomerWebAuthnCredential";

DROP FUNCTION IF EXISTS app_public.delete_customer_passkey(text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.list_customer_passkeys(text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.finish_customer_passkey(text,text[],text,jsonb,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.load_customer_passkey(text[],text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.begin_customer_passkey(text,text,text,text,text,text,text,text,text,text,timestamp without time zone,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.accept_customer_ownership_transfer(text,text,text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.cancel_customer_ownership_transfer(text,text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.create_customer_ownership_transfer(text,text,text,text,timestamp without time zone,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.claim_customer_ownership(text,text,text,text,text,text,boolean,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.public_verify_write_evidence(text,text,text,text,jsonb,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.revoke_customer_auth_session(text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.read_customer_auth_session(text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.require_customer_auth_session(text,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_public.issue_customer_auth_session(text,text,text,text,text,timestamp without time zone,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.complete_public_support_delivery(text,text,text,text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.track_support_status(text,text,integer,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.complete_request_access_delivery(text,text,text,text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.submit_public_support(text,text,text,text,text,text,text,text,text,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_public.submit_request_access(text,text,text,text,text,text,text,text,text,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_public.submit_public_incident(text,text,text,text,text,boolean,jsonb,timestamp without time zone,text,text,text,text);
DROP FUNCTION IF EXISTS app_public.submit_product_feedback(text,integer,text,text,text,text,text,timestamp without time zone,text,text,text);
DROP FUNCTION IF EXISTS app_public.write_verification_session(text,text,text,text,jsonb,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.read_verification_session(text,text,text,timestamp without time zone,text);
DROP FUNCTION IF EXISTS app_public.start_verification_session(text,text,text,timestamp without time zone,text,text);
DROP FUNCTION IF EXISTS app_public.record_qr_verification(text,text,text,timestamp without time zone,text,text,text);
DROP FUNCTION IF EXISTS app_public.verify_signed_qr(text,text,text,text,text,text,integer,text,timestamp without time zone,timestamp without time zone,timestamp without time zone,text,text,text,text);
DROP FUNCTION IF EXISTS app_public.verify_raw_qr(text,timestamp without time zone,text,text,text,text);
DROP FUNCTION IF EXISTS app_public.public_verify_execute(text,text,timestamp without time zone,text,text,text,text,text);
DROP FUNCTION IF EXISTS app_public.public_verify_bind(text,text,text,text,text,text,text);
