DROP POLICY IF EXISTS qr_system_securityeventoutbox_insert ON public."SecurityEventOutbox";
DROP POLICY IF EXISTS qr_system_auditlog_insert ON public."AuditLog";
DROP POLICY IF EXISTS qr_system_allocationevent_insert ON public."AllocationEvent";
DROP POLICY IF EXISTS qr_system_qrallocationrequest_update ON public."QrAllocationRequest";
DROP POLICY IF EXISTS qr_system_qrallocationrequest_select ON public."QrAllocationRequest";
DROP POLICY IF EXISTS qr_system_batch_delete ON public."Batch";
DROP POLICY IF EXISTS qr_system_batch_update ON public."Batch";
DROP POLICY IF EXISTS qr_system_batch_insert ON public."Batch";
DROP POLICY IF EXISTS qr_system_batch_select ON public."Batch";
DROP POLICY IF EXISTS qr_system_policyalert_select ON public."PolicyAlert";
DROP POLICY IF EXISTS qr_system_traceevent_select ON public."TraceEvent";
DROP POLICY IF EXISTS qr_system_qrcode_delete ON public."QRCode";
DROP POLICY IF EXISTS qr_system_qrcode_update ON public."QRCode";
DROP POLICY IF EXISTS qr_system_qrcode_insert ON public."QRCode";
DROP POLICY IF EXISTS qr_system_qrcode_select ON public."QRCode";
DROP POLICY IF EXISTS qr_system_qrrange_insert ON public."QRRange";
DROP POLICY IF EXISTS qr_system_qrrange_select ON public."QRRange";
DROP POLICY IF EXISTS qr_system_user_select ON public."User";
DROP POLICY IF EXISTS qr_system_manufacturerlicenseelink_select ON public."ManufacturerLicenseeLink";
DROP POLICY IF EXISTS qr_system_licensee_select ON public."Licensee";
DROP POLICY IF EXISTS qr_system_organization_select ON public."Organization";
DROP POLICY IF EXISTS qr_system_systemcheckpoint_update ON public."SystemCheckpoint";
DROP POLICY IF EXISTS qr_system_systemcheckpoint_insert ON public."SystemCheckpoint";
DROP POLICY IF EXISTS qr_system_systemcheckpoint_select ON public."SystemCheckpoint";
DROP POLICY IF EXISTS qr_system_scanmetricshourlyrollup_update ON public."ScanMetricsHourlyRollup";
DROP POLICY IF EXISTS qr_system_scanmetricshourlyrollup_insert ON public."ScanMetricsHourlyRollup";
DROP POLICY IF EXISTS qr_system_scanmetricshourlyrollup_select ON public."ScanMetricsHourlyRollup";
DROP POLICY IF EXISTS qr_system_qrscanlog_select ON public."QrScanLog";
DROP POLICY IF EXISTS qr_system_inventorystatusrollup_update ON public."InventoryStatusRollup";
DROP POLICY IF EXISTS qr_system_inventorystatusrollup_insert ON public."InventoryStatusRollup";
DROP POLICY IF EXISTS qr_system_inventorystatusrollup_select ON public."InventoryStatusRollup";

DROP FUNCTION IF EXISTS app_rls.refresh_scan_metrics_hourly_rollups(text);
DROP FUNCTION IF EXISTS app_rls.refresh_inventory_status_rollups(text);
DROP FUNCTION IF EXISTS app_rls.qr_approve_allocation_request(text,text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.qr_batch_command(text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.qr_bind_break_glass_tokens(text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.qr_get_code_scope(text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.qr_delete_codes(text,text,text,text[],text[]);
DROP FUNCTION IF EXISTS app_rls.qr_export_codes(text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.qr_inventory_projection(text,text,text,text,text,text,text,text,integer,integer);
DROP FUNCTION IF EXISTS app_rls.qr_stats(text,text,text,text);
DROP FUNCTION IF EXISTS app_rls.qr_read_codes(text,text,text,text,text,text,integer,integer);
DROP FUNCTION IF EXISTS app_rls.qr_allocate_range(text,text,text,text,integer,integer,text,text);
DROP FUNCTION IF EXISTS app_rls.qr_write_audit(text,text,text,text,text,text,jsonb);
DROP FUNCTION IF EXISTS app_rls.qr_bind_actor(text,text,text,text);
